language: node_js
os: windows
before_script:
  - cd tsStore
 
env:
  - workerCount=3 timeout=600000

branches:
  only:
  - master

install:
  - npm i -g typescript
  - npm install

cache:
  directories:
    - node_modules
script: 
  npm run build
