language: node_js
  
before_script:
  - cd tsStore
 

env:
  - workerCount=3 timeout=600000

branches:
  only:
  - master

install:
  - apt install node-typescript
  - npm install -g concurrently
  - npm install -g typescript
  - npm install -g lite-server
  - npm install

cache:
  directories:
    - node_modules
script: 
  npm run build
