language node_js

node_js
  - 'node'
  - '10'
  - '8'
  
before_script
  - cd tsStore

env
  - workerCount=3 timeout=600000

matrix
  fast_finish true

branches
  only
  - master

install
  - npm install

cache
  directories
    - node_modules

git
  depth 1
