language: node_js

before_script:
  - cd tsStore
 
env:
  - workerCount=3 timeout=600000

branches:
  only:
  - master

install:
  - npm i -g typescript@3.7.2

cache:
  directories:
    - node_modules
script: 
  npm run build
