language: node_js

before_script:
  - cd tsStore
 
env:
  - workerCount=3 timeout=600000

branches:
  only:
  - master

install:
  - npm uninstall typescript --no-save
  - npm i -g typescript@3.7.2

script:
  npm ci
  npm run build
