language: node_js
  
before_script:
  - cd tsStore
 
env:
  - workerCount=3 timeout=600000

branches:
  only:
  - master

install:
  - npm install -g typescript
  - npm install

cache:
  directories:
    - node_modules
script: 
  echo "npm test temporarily disabled"
